<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hexdump</string>
	</array>
	<key>name</key>
	<string>Hex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^(\s\sOffset:\s).*$</string>
			<key>name</key>
			<string>keyword.header.hex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([a-fA-F\d]{8}:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.address.hex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>dump.buffer-start.hex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[\s]{2}</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ascii-start.hex</string>
				</dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>dump.buffer-end.hex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>dump.hex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[\da-fA-F]{1}</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>raw.nibble.upper.hex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>[\da-fA-F]{1}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>raw.nibble.lower.hex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>raw.byte.hex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[\w\W]</string>
							<key>name</key>
							<string>invalid.illegal.expected-nibble.hex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[\s]{1}</string>
					<key>name</key>
					<string>raw.punctuation.hex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\w\W]{1}\s*</string>
					<key>name</key>
					<string>invalid.illegal.character.hex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>.*$</string>
			<key>name</key>
			<string>comment.ascii.hex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hexdump</string>
	<key>uuid</key>
	<string>B8374ECF-69FA-40C0-8CEA-385C4AA08663</string>
</dict>
</plist>